---
# Runs on Thursday after FerretDB repo.
# Apply the "not ready" label to prevent cascaded CI runs on each auto-merge.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"

  - package-ecosystem: "docker"
    directory: "/build/deps"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      build-deps:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"

  - package-ecosystem: "gomod"
    directory: "/"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      dance:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"
  - package-ecosystem: "gomod"
    directory: "/tools"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      tools:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"
  - package-ecosystem: "gomod"
    directory: "/tools/golangci"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    groups:
      tools:
        patterns: ["*"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    labels: ["deps", "not ready"]
    assignees: [AlekSi]
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:42"
